// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHfKQzKDCnttBZSxaNQ6mrs7whl3u6aow',
    appId: '1:57230187702:web:b67c3444a613bfc884da17',
    messagingSenderId: '57230187702',
    projectId: 'themar-app-75c5e',
    authDomain: 'themar-app-75c5e.firebaseapp.com',
    storageBucket: 'themar-app-75c5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0VGsNyUAit5BzXkWSS4oH-zfJsIonT8',
    appId: '1:57230187702:android:008a488df427a53884da17',
    messagingSenderId: '57230187702',
    projectId: 'themar-app-75c5e',
    storageBucket: 'themar-app-75c5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI3y6y6GO6tUzAduGFwYHVhYsOo0S91Vc',
    appId: '1:57230187702:ios:a9b51efd1f2369e984da17',
    messagingSenderId: '57230187702',
    projectId: 'themar-app-75c5e',
    storageBucket: 'themar-app-75c5e.firebasestorage.app',
    iosBundleId: 'com.example.thimarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI3y6y6GO6tUzAduGFwYHVhYsOo0S91Vc',
    appId: '1:57230187702:ios:a9b51efd1f2369e984da17',
    messagingSenderId: '57230187702',
    projectId: 'themar-app-75c5e',
    storageBucket: 'themar-app-75c5e.firebasestorage.app',
    iosBundleId: 'com.example.thimarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHfKQzKDCnttBZSxaNQ6mrs7whl3u6aow',
    appId: '1:57230187702:web:5bf78b3f948dbc6984da17',
    messagingSenderId: '57230187702',
    projectId: 'themar-app-75c5e',
    authDomain: 'themar-app-75c5e.firebaseapp.com',
    storageBucket: 'themar-app-75c5e.firebasestorage.app',
  );
}
